language: generic 
sudo: required
services: 
  - docker

before_install:
    - docker build -t kavitesh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kavitesh/react-test npm test
#  - docker run kavitesh/react-test npm test -- --coverage

after_success:
    - docker build -t kavitesh/multi-client ./client
    - docker build -t kavitesh/multi-nginx ./nginx
    - docker build -t kavitesh/multi-server ./server
    - docker build -t kavitesh/multi-worker ./worker
    # login docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push images to docker hub
    - docker push kavitesh/multi-client
    - docker push kavitesh/multi-nginx
    - docker push kavitesh/multi-server
    - docker push kavitesh/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
